### ISSUE TITLE
SPARSESOS with free solvers?

### ISSUE THREAD

**Issue by PoeticExposition** [lihaokun/sparsesos#1]
MOSEK 10 has been released recently, but unfortunately, I am not in a degree-granting institution now, so I can no longer access a Personal Academic license. In accordance with [https://yalmip.github.io/allsolvers/#semidefinite-programming-free](url), several open-source solvers with C API (e.g., [SCS](https://www.cvxgrp.org/scs/), [CSDP](https://projects.coin-or.org/Csdp), [SDPA](https://sdpa.sourceforge.net/), [SDPLR](http://sburer.github.io/projects.html), and [DSDP](https://www.mcs.anl.gov/hs/software/DSDP/)) are available. Since the OS of my computer is Windows (instead of Linux) and I still don't intend installing WSL, is it possible to use other noncommercial SDP solvers in the SparseSoS on a Windows machine?

**Comment by lihaokun** [comment]
Yes, you can use non-commercial SDP solvers with SparseSoS on a Windows machine. The calls to MOSEK API in the previous versions of SparseSoS can be replaced with the APIs of other solvers by modifying the file `sparsesos/src/sos_mosek.cpp`. While  I plan to add support for multiple backends in the future, this may take some time. In the meantime, you may consider making modifications to the `sos_mosek.cpp` file to achieve the desired functionality with the non-commercial solver of your choice. Your contribution to the development of SparseSoS will be highly appreciated. Please let me know if you have any other questions or concerns.
